AdressBook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from register import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AdressBook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/', include('register.urls')),
    #url(r'^register/(?P<contact_id>\d+)/$', include('register.urls')),
    #url(r'^register/(?P<contact_id>\d+)/location/$', include('register.urls')),
    #url(r'^register/(?P<contact_id>\d+)/location/(?P<location_id>\d+)/$', include('register.urls')),
)

register/urls.py
from django.conf.urls import patterns, url
from register import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AdressBook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<contact_id>\d+)/$', views.index, name = 'edit_contact'),
    url(r'^(?P<contact_id>\d+)/location/$', views.editLocation, name = 'locations'),
    url(r'^(?P<contact_id>\d+)/location/(?P<location_id>\d+)/$', views.editLocation, name = 'edit_locations'),
)

register/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    firstName = models.CharField(max_length = 20)
    lastName = models.CharField(max_length = 20)
    company = models.CharField(max_length = 20)
    def __str__(self):
        return self.firstName + ' ' + self.lastName

class Location(models.Model):
    contact = models.ForeignKey(Contact)
    name = models.CharField(max_length = 20)
    def __str__(self):
        return self.name

class LocationInfo(models.Model):
    ADDRESS = 'Address'
    PHONE = 'Phone'
    MAIL = 'Mail'
    TYPE_CHOICE = ((ADDRESS, 'Address'), (PHONE, 'Phone'), (MAIL, 'Mail'))
    location = models.ForeignKey(Location)
    type = models.CharField(max_length=20, choices=TYPE_CHOICE, default=ADDRESS)
    value = models.CharField(max_length=255)

register/forms.py
__author__ = 'agiles'

from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from register.models import Contact, Location, LocationInfo

class ContactForm(ModelForm):
    class Meta:
        model = Contact

class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = ['name']

LocationInfoFormSet = inlineformset_factory(Location,LocationInfo, can_delete=False, extra=1)

register/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.template import RequestContext, loader

from register.models import Contact
from register.models import Location
from register.models import LocationInfo
from forms import ContactForm, LocationInfoFormSet, LocationForm

# Create your views here.
def index(request, contact_id=None):
    contactInstance = None

    if contact_id:
        contactInstance = get_object_or_404(Contact, pk=contact_id)


    form = ContactForm(request.POST or None, instance=contactInstance)
    if form.is_valid():

        form.save(  )
        return HttpResponseRedirect('/register/')

    if 'q' in request.GET and request.GET['q']:
        search = request.GET['q']
        contactList = Contact.objects.filter(Q(firstName__icontains=search) | Q(lastName__icontains=search)).order_by('lastName')
    else:
        contactList = Contact.objects.order_by('lastName')
    context= {'contactList': contactList,'form': form}
    return render(request,'register/index.html',context)

def editLocation(request, contact_id=None, location_id=None):
    contactInstance = get_object_or_404(Contact, pk=contact_id)
    locationInstance = Location()
    locationInstance.contact=contactInstance

    if location_id:
        locationInstance = get_object_or_404(Location, pk=location_id)


    form = LocationForm(request.POST or None, instance=locationInstance)
    formSet = LocationInfoFormSet(request.POST or None, instance=locationInstance)
    if form.is_valid():
        loc = form.save(commit=False)
        if formSet.is_valid():
            loc.save()
            formSet.save()
            return HttpResponseRedirect(request.path)


    locationList = Location.objects.all()

    context = {'locationList': locationList,'form':form, 'formSet': formSet, 'contactInstance': contactInstance}

    return render(request, 'register/location.html', context)

register/templates/register/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

register/templates/register/location.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<a href="{% url 'index' %}"> Atras </a>

<h1>  Localizaciones </h1>
<h2>{{ contactInstance.firstName }} {{ contactInstance.lastName }}</h2>

<form action="{{ request.path }} " method="post">
    {% csrf_token %}
    {{ form }}
    <table>
        {{ formSet.as_table }}
        {{ formSet.management_form }}
    </table>

    <input type="submit" value="Enviar"/>
</form>

{% if contactInstance.location_set.all %}
    <ul>
    {% for location in contactInstance.location_set.all %}
        <li><a >{{location.name}}</a>    <a href="/register/{{ contactInstance.id }}/location/{{ location.id }}/">Editar</a></li>
        <ul>
            {% for info in location.locationinfo_set.all %}
                <li><a>{{ info.type }}: {{ info.value }}</a></li>
            {% endfor %}
        </ul>
    {% endfor %}
    </ul>
{% else %}
    <p>No tiene locaciones registradas.</p>
{% endif %}


</body>
</html>